//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace orGenta {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class orGentaResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal orGentaResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("orGenta.orGentaResources", typeof(orGentaResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About orGenta.
        /// </summary>
        internal static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        internal static string AddCategory {
            get {
                return ResourceManager.GetString("AddCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orGenta is already running.
        /// </summary>
        internal static string AlreadyRunning {
            get {
                return ResourceManager.GetString("AlreadyRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect registration number entered.
        /// </summary>
        internal static string BadRegistration {
            get {
                return ResourceManager.GetString("BadRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orGenta Calendar.
        /// </summary>
        internal static string CalendarTitle {
            get {
                return ResourceManager.GetString("CalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Categories ....
        /// </summary>
        internal static string CategoriesTitle {
            get {
                return ResourceManager.GetString("CategoriesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorizing New Items ....
        /// </summary>
        internal static string Categorizing {
            get {
                return ResourceManager.GetString("Categorizing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change to Internal Links.
        /// </summary>
        internal static string chgInternal {
            get {
                return ResourceManager.GetString("chgInternal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility synchronizes your Category view;with the items in the orGenta database;and removes duplicate items . . .;Is it okay to proceed?.
        /// </summary>
        internal static string CleanupWarning {
            get {
                return ResourceManager.GetString("CleanupWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comma Separated Files|*.csv.
        /// </summary>
        internal static string CommaSep {
            get {
                return ResourceManager.GetString("CommaSep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming . . ..
        /// </summary>
        internal static string Confirming {
            get {
                return ResourceManager.GetString("Confirming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        internal static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select how you would like the notes converted:.
        /// </summary>
        internal static string ConvChoicePrompt {
            get {
                return ResourceManager.GetString("ConvChoicePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This utility converts the notes on the currently visible items, changing them into their own items.  The original items will still retain their notes too..
        /// </summary>
        internal static string ConvsnDescriptive {
            get {
                return ResourceManager.GetString("ConvsnDescriptive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orGenta   ;Organizing software for gentlemen;Copyright (c)2005, 2006 J.D. Chapman;All Rights Reserved.
        /// </summary>
        internal static string CopyrightNotice {
            get {
                return ResourceManager.GetString("CopyrightNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: dB is not current!.
        /// </summary>
        internal static string dbVsnErr {
            get {
                return ResourceManager.GetString("dbVsnErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete category &quot;.
        /// </summary>
        internal static string DeleteCat {
            get {
                return ResourceManager.GetString("DeleteCat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description on Page&apos;s META Tag.
        /// </summary>
        internal static string DescrMeta {
            get {
                return ResourceManager.GetString("DescrMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Item Completely.
        /// </summary>
        internal static string Discard {
            get {
                return ResourceManager.GetString("Discard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove or Discard?.
        /// </summary>
        internal static string DisposeTitle {
            get {
                return ResourceManager.GetString("DisposeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey! This will remove ALL the categories except the starting;seeds and and leave your items in the Unassigned category!;Is it okay to proceed?.
        /// </summary>
        internal static string DropCatWarning {
            get {
                return ResourceManager.GetString("DropCatWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter.
        /// </summary>
        internal static string Enter {
            get {
                return ResourceManager.GetString("Enter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --&gt; Enter a new Item, or a single word to Search.
        /// </summary>
        internal static string EntryPrompt {
            get {
                return ResourceManager.GetString("EntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select Item rows to assign first....
        /// </summary>
        internal static string errSelectItems {
            get {
                return ResourceManager.GetString("errSelectItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an Item row first....
        /// </summary>
        internal static string errSelectItemsV2 {
            get {
                return ResourceManager.GetString("errSelectItemsV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Fields . . ..
        /// </summary>
        internal static string FieldsTitle {
            get {
                return ResourceManager.GetString("FieldsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Text Line of the Page.
        /// </summary>
        internal static string FirstLine {
            get {
                return ResourceManager.GetString("FirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Closed.
        /// </summary>
        internal static string FreezeClosed {
            get {
                return ResourceManager.GetString("FreezeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click and Type new item here.
        /// </summary>
        internal static string gridEntryPrompt {
            get {
                return ResourceManager.GetString("gridEntryPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mailing Address.
        /// </summary>
        internal static string hdrAddress {
            get {
                return ResourceManager.GetString("hdrAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell Ph#.
        /// </summary>
        internal static string hdrCellPhone {
            get {
                return ResourceManager.GetString("hdrCellPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string hdrDone {
            get {
                return ResourceManager.GetString("hdrDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to e-Mail Address.
        /// </summary>
        internal static string hdrEmail {
            get {
                return ResourceManager.GetString("hdrEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered.
        /// </summary>
        internal static string hdrEntered {
            get {
                return ResourceManager.GetString("hdrEntered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        internal static string hdrFinished {
            get {
                return ResourceManager.GetString("hdrFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home Ph#.
        /// </summary>
        internal static string hdrHomePhone {
            get {
                return ResourceManager.GetString("hdrHomePhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item.
        /// </summary>
        internal static string hdrItem {
            get {
                return ResourceManager.GetString("hdrItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string hdrKey {
            get {
                return ResourceManager.GetString("hdrKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string hdrNote {
            get {
                return ResourceManager.GetString("hdrNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prty.
        /// </summary>
        internal static string hdrPriority {
            get {
                return ResourceManager.GetString("hdrPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When.
        /// </summary>
        internal static string hdrWhen {
            get {
                return ResourceManager.GetString("hdrWhen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Ph#.
        /// </summary>
        internal static string hdrWorkPhone {
            get {
                return ResourceManager.GetString("hdrWorkPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internet Link.
        /// </summary>
        internal static string hdrWww {
            get {
                return ResourceManager.GetString("hdrWww", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Done.
        /// </summary>
        internal static string HideDone {
            get {
                return ResourceManager.GetString("HideDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Icons by.
        /// </summary>
        internal static string IconCredit {
            get {
                return ResourceManager.GetString("IconCredit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Completed.
        /// </summary>
        internal static string ImportCompleted {
            get {
                return ResourceManager.GetString("ImportCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importing Items ....
        /// </summary>
        internal static string Importing {
            get {
                return ResourceManager.GetString("Importing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Item Import File.
        /// </summary>
        internal static string ImportItemPrompt {
            get {
                return ResourceManager.GetString("ImportItemPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For imported Item text, use:.
        /// </summary>
        internal static string ImportLabel {
            get {
                return ResourceManager.GetString("ImportLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orGenta;Organizing software for gentlemen;;Thank you for registering orGenta! Please enter the registration key that you obtained in e-Mail below:.
        /// </summary>
        internal static string KeyPrompt {
            get {
                return ResourceManager.GetString("KeyPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave as Web Links.
        /// </summary>
        internal static string LeaveLinks {
            get {
                return ResourceManager.GetString("LeaveLinks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow links through how many levels:.
        /// </summary>
        internal static string LinkDepth {
            get {
                return ResourceManager.GetString("LinkDepth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading . . ..
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string mnuAbout {
            get {
                return ResourceManager.GetString("mnuAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Print.
        /// </summary>
        internal static string mnuAdvancedPrint {
            get {
                return ResourceManager.GetString("mnuAdvancedPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign To....
        /// </summary>
        internal static string mnuAssign {
            get {
                return ResourceManager.GetString("mnuAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calendar.
        /// </summary>
        internal static string mnuCalendar {
            get {
                return ResourceManager.GetString("mnuCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cleanup Items.
        /// </summary>
        internal static string mnuCleanup {
            get {
                return ResourceManager.GetString("mnuCleanup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string mnuCollapseAll {
            get {
                return ResourceManager.GetString("mnuCollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Node.
        /// </summary>
        internal static string mnuCollapseNode {
            get {
                return ResourceManager.GetString("mnuCollapseNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color Reset.
        /// </summary>
        internal static string mnuColorReset {
            get {
                return ResourceManager.GetString("mnuColorReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string mnuDelete {
            get {
                return ResourceManager.GetString("mnuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drop Categories.
        /// </summary>
        internal static string mnuDropCats {
            get {
                return ResourceManager.GetString("mnuDropCats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string mnuEdit {
            get {
                return ResourceManager.GetString("mnuEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        internal static string mnuExit {
            get {
                return ResourceManager.GetString("mnuExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string mnuExpandAll {
            get {
                return ResourceManager.GetString("mnuExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Node.
        /// </summary>
        internal static string mnuExpandNode {
            get {
                return ResourceManager.GetString("mnuExpandNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Only This.
        /// </summary>
        internal static string mnuExpandThis {
            get {
                return ResourceManager.GetString("mnuExpandThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export CSV.
        /// </summary>
        internal static string mnuExportCSV {
            get {
                return ResourceManager.GetString("mnuExportCSV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Tabbed.
        /// </summary>
        internal static string mnuExportTabbed {
            get {
                return ResourceManager.GetString("mnuExportTabbed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string mnuFile {
            get {
                return ResourceManager.GetString("mnuFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Category.
        /// </summary>
        internal static string mnuFindCategory {
            get {
                return ResourceManager.GetString("mnuFindCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Item.
        /// </summary>
        internal static string mnuFindItem {
            get {
                return ResourceManager.GetString("mnuFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string mnuFindNext {
            get {
                return ResourceManager.GetString("mnuFindNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Note.
        /// </summary>
        internal static string mnuFindNote {
            get {
                return ResourceManager.GetString("mnuFindNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Freeze Closed.
        /// </summary>
        internal static string mnuFreezeClosed {
            get {
                return ResourceManager.GetString("mnuFreezeClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        internal static string mnuHelp {
            get {
                return ResourceManager.GetString("mnuHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Items.
        /// </summary>
        internal static string mnuImportItems {
            get {
                return ResourceManager.GetString("mnuImportItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Web....
        /// </summary>
        internal static string mnuImportWeb {
            get {
                return ResourceManager.GetString("mnuImportWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Print.
        /// </summary>
        internal static string mnuItemPrint {
            get {
                return ResourceManager.GetString("mnuItemPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notes To Items.
        /// </summary>
        internal static string mnuNotesToItems {
            get {
                return ResourceManager.GetString("mnuNotesToItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs Again.
        /// </summary>
        internal static string mnuOccursAgain {
            get {
                return ResourceManager.GetString("mnuOccursAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Print.
        /// </summary>
        internal static string mnuPagePrint {
            get {
                return ResourceManager.GetString("mnuPagePrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Setup....
        /// </summary>
        internal static string mnuPrinterSetup {
            get {
                return ResourceManager.GetString("mnuPrinterSetup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Item.
        /// </summary>
        internal static string mnuPrintItem {
            get {
                return ResourceManager.GetString("mnuPrintItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Widths.
        /// </summary>
        internal static string mnuResetWidths {
            get {
                return ResourceManager.GetString("mnuResetWidths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Done.
        /// </summary>
        internal static string mnuShowDone {
            get {
                return ResourceManager.GetString("mnuShowDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Categories.
        /// </summary>
        internal static string mnuSortCategories {
            get {
                return ResourceManager.GetString("mnuSortCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort Items.
        /// </summary>
        internal static string mnuSortItems {
            get {
                return ResourceManager.GetString("mnuSortItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        internal static string mnuTools {
            get {
                return ResourceManager.GetString("mnuTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trayed Mode.
        /// </summary>
        internal static string mnuTrayed {
            get {
                return ResourceManager.GetString("mnuTrayed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string mnuView {
            get {
                return ResourceManager.GetString("mnuView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Item.
        /// </summary>
        internal static string mnuZoomItem {
            get {
                return ResourceManager.GetString("mnuZoomItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preferences for Notes to Items.
        /// </summary>
        internal static string N2Ititle {
            get {
                return ResourceManager.GetString("N2Ititle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No More Repeats Found.
        /// </summary>
        internal static string NoMoreRepeats {
            get {
                return ResourceManager.GetString("NoMoreRepeats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Note text here . . ..
        /// </summary>
        internal static string NotePrompt {
            get {
                return ResourceManager.GetString("NotePrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note Data.
        /// </summary>
        internal static string NoteTitle {
            get {
                return ResourceManager.GetString("NoteTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Found.
        /// </summary>
        internal static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Links to Imported Pages:.
        /// </summary>
        internal static string OnLinksLabel {
            get {
                return ResourceManager.GetString("OnLinksLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Unfrozen.
        /// </summary>
        internal static string OpenUnfrozen {
            get {
                return ResourceManager.GetString("OpenUnfrozen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pause.
        /// </summary>
        internal static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Item per paragraph.
        /// </summary>
        internal static string PerParagraph {
            get {
                return ResourceManager.GetString("PerParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One Item per sentence.
        /// </summary>
        internal static string PerSentence {
            get {
                return ResourceManager.GetString("PerSentence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Register.
        /// </summary>
        internal static string PleaseRegister {
            get {
                return ResourceManager.GetString("PleaseRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        internal static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orGenta Printing Options.
        /// </summary>
        internal static string PrintOptions {
            get {
                return ResourceManager.GetString("PrintOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical registration failure: .
        /// </summary>
        internal static string RegistrationFailure {
            get {
                return ResourceManager.GetString("RegistrationFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Mail.
        /// </summary>
        internal static string RegistrationMail {
            get {
                return ResourceManager.GetString("RegistrationMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to orGenta;Organizing software for gentlemen;;orGenta is shareware!  We encourage you to share this software with your friends, but we also would like you to register!;;Registration costs U.S. $10;;To register please send an e-Mail with your Software ID (listed below, or click on the &quot;Registration Mail&quot; button)..
        /// </summary>
        internal static string RegistrationNotice {
            get {
                return ResourceManager.GetString("RegistrationNotice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Required.
        /// </summary>
        internal static string RegistrationRequired {
            get {
                return ResourceManager.GetString("RegistrationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Item from Category.
        /// </summary>
        internal static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore.
        /// </summary>
        internal static string Restore {
            get {
                return ResourceManager.GetString("Restore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        internal static string Resume {
            get {
                return ResourceManager.GetString("Resume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saving Database ....
        /// </summary>
        internal static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (scanning from this page alphabetically starting with:).
        /// </summary>
        internal static string scanAlpha {
            get {
                return ResourceManager.GetString("scanAlpha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search For:.
        /// </summary>
        internal static string SearchPrompt {
            get {
                return ResourceManager.GetString("SearchPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or Select File to Export to ....
        /// </summary>
        internal static string SelectExportFile {
            get {
                return ResourceManager.GetString("SelectExportFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Done.
        /// </summary>
        internal static string ShowDone {
            get {
                return ResourceManager.GetString("ShowDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip.
        /// </summary>
        internal static string Skip {
            get {
                return ResourceManager.GetString("Skip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbed Text File|*.txt.
        /// </summary>
        internal static string TabbedText {
            get {
                return ResourceManager.GetString("TabbedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Files|*.txt|All Files|*.*.
        /// </summary>
        internal static string TextAndAllFiles {
            get {
                return ResourceManager.GetString("TextAndAllFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank You, your software is registered!.
        /// </summary>
        internal static string ThanksRegistered {
            get {
                return ResourceManager.GetString("ThanksRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timeout (secs):.
        /// </summary>
        internal static string Timeout {
            get {
                return ResourceManager.GetString("Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --&gt; Enter a new Item, or a single word to Search.
        /// </summary>
        internal static string TrayedPrompt {
            get {
                return ResourceManager.GetString("TrayedPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First sentence in the pargraph becomes the item.
        /// </summary>
        internal static string UseFirst {
            get {
                return ResourceManager.GetString("UseFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last sentence in the pargraph becomes the item.
        /// </summary>
        internal static string UseLast {
            get {
                return ResourceManager.GetString("UseLast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type or Paste Web Address:.
        /// </summary>
        internal static string WebAddrPrompt {
            get {
                return ResourceManager.GetString("WebAddrPrompt", resourceCulture);
            }
        }
    }
}
